### ISSUE TITLE
Pulling this into zig-objcopy

### ISSUE THREAD

**Issue by SpieringsAE** [bcrist/Zig-S-Records#1]
I would like to try to merge this code into the zig objcopy tool so we can actually create srec with that.
Is that okay with you?

**Comment by bcrist** [comment]
Do you mean `std.Build.Step.ObjCopy`?  If you want to open a zig proposal that's fine by me, but I'm unsure if it would be accepted.  Be sure to include your specific real-world use case(s) where having it in the `std` would be helpful.

Also note that my personal code style uses `snake_case` for function names, whereas `std` uses `camelCase`, so some adjustments would be needed for that, and I haven't worked on a project using this lib for a while; it may need some fixes to work with zig 0.12/0.13/master

**Comment by SpieringsAE** [comment]
I was thinking into [this](https://github.com/ziglang/zig/blob/master/lib/compiler/objcopy.zig), but I guess the std.Build.Step.ObjCopy calls that one, so it should be done in both

My intention is to use it with a makefile as I am sadly stuck to those in this situation, its actually curious why these are seperate, maybe it is too difficult to integrate them.

Sadly there seems to be no possibility to make a zig proposal at this time so I'm just going to try to get it working for the hell of it and try to put in the pull request as more of a bonus.

**Comment by bcrist** [comment]
The zig issue templates are set up that way in order to avoid being overwhelmed by "drive by" language proposals from people who haven't even used the language but just want to see feature XYZ added from their favorite language.

I'd suggest bringing it up on the [zig discord](https://discord.gg/vbaFshvj)
